#   _____                _      _____ _
#  / ____|              | |    / ____| |
# | |     _ __ __ _  ___| |__ | (___ | |__   ___  _ __
# | |    | '__/ _` |/ __| '_ \ \___ \| '_ \ / _ \| '_ \
# | |____| | | (_| | (__| | | |____) | | | | (_) | |_) |
#  \_____|_|  \__,_|\___|_| |_|_____/|_| |_|\___/| .__/
#                                                | |
#                                                |_|
#Every item can have these characteristic:
#diamond_sword: <-- Item ID
# material: DIAMOND_SWORD <-- Only mandatory feature
# amount: 2 <-- Default is 1
# displayname: "<aqua>OP Diamond Sword" <-- Minimessage Support!
# custom-model-data: 0 <-- Giving an item a custom model throw a texture pack
# item-model: "opsword"
# enchantments: <-- You can give any enchantment you want!
#   minecraft:sharpness:5
# lore:
# - <red>this sword is OP!
# glow: true <-- Default is false

general-items:
  back:
    material: ARROW
    displayname: "<red>Previous Page"
  next:
    material: ARROW
    displayname: "<green>Next Page"
  main:
    material: BARRIER
    displayname: "<red>Back"
    slot: 49
  filler:
    enabled: true
    material: BLACK_STAINED_GLASS_PANE
    displayname: ""